# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: bearlybits
email: jeffrey@bearlybits.com
description: > # this means to ignore newlines until "baseurl:"
  bearlybits is an intersection of travel,
  photography, languages, and code.
  Oh and hopefully, a bit of fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bearlybits.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kumajeff
github_username:  rallykuma

excerpt_separator: <!--more-->

paginate_multiple:
  - paginate: 3
    paginate_path: '/page:num/'
    sub_dir: ''
  - paginate: 9
    paginate_path: '/blog/page:num/'
    sub_dir: ''

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-multiple
exclude:
  - Gemfile
  - Gemfile.lock
